django_app/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf.urls import include
from django.views.static import serve as dj_v_serve
from . import views
import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('user_authentication.urls')),
    url(r'^notes/', include('notes.urls')),
    url(r'^$', views.main_page, name='main_page'),
    url(r'^grades/', include('grades.urls')),
    url(r'^kalendar/', include('kalendar.urls')),
    url(r'^poll/', include('poll.urls', namespace='poll')),
    url(r'^media/(.*)$', dj_v_serve, {'document_root' : settings.MEDIA_ROOT}),
    url(r'^ocr/', include('ocr.urls', namespace='ocr')),
    url(r'^notice_board/', include('notice_board.urls', namespace='notice_board', app_name='notice_board')),
]

notice_board/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [url(r'^$', views.list_post, name='post_list'),
               url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/'r'(?P<post>[-\w]+)/$',
                   views.post_detail, name='post_detail'),
               url(r'^add_post/$', views.add_post, name='add_post'),
               url(r'^edit_post/(?P<pk>\d+)/$',
                   views.edit, name='edit_post'),
               url(r'^delete_post/(?P<pk>\d+)/$',
                   views.delete, name='delete_post'),
]

ocr/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url('^$', views.index, name='index'),
    url(r'^(?P<classes>[A-Za-z0-9-]+)/(?P<lecture_number>[0-9]+)/add_ocr/$',
        views.add_ocr, name='add_ocr'),
    url(r'^(?P<classes>[A-Za-z0-9-]+)/(?P<lecture_number>[0-9]+)/add_crop/$',
        views.add_crop, name='add_crop'),
]

notice_board/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.utils.text import slugify


class Post(models.Model):
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250,
                            unique_for_date='publish')
    author = models.ForeignKey(User)
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-publish',)

    def save(self, *args, **kwargs):
        if not self.id:
            slug = slugify(self.title)
            if Post.objects.filter(slug=slug).exists():
                self.slug = slugify(self.title) + '-{}'.format(Post.objects.count())
            else:
                self.slug = slugify(self.title)
        super(Post, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('notice_board:post_detail',
                       args=[self.publish.year,
                             self.publish.strftime('%m'),
                             self.publish.strftime('%d'),
                             self.slug])


class Comment(models.Model):
    post = models.ForeignKey(Post, related_name='comments')
    name = models.CharField(max_length=80)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

notice_board/forms.py
from .models import Comment, Post
from django import forms
from django.utils.text import slugify
from django.core.exceptions import ValidationError


class PostForm(forms.ModelForm):
    body = forms.CharField(widget=forms.Textarea(attrs={'cols': 50, 'rows': 5, 'style': 'resize:none;'}),
                           label='Content')

    class Meta:
        model = Post
        fields = ('title', 'body', 'author', 'slug')
        exclude = ["slug", "author"]


class CommentForm(forms.ModelForm):
    body = forms.CharField(widget=forms.Textarea(attrs={'cols': 50, 'rows': 5, 'style': 'resize:none;'}), label='')

    class Meta:
        model = Comment
        fields = ('body', 'name')
        exclude = ["name"]

notice_board/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render, get_object_or_404
from .models import Post, Comment
from .forms import CommentForm, PostForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseForbidden


@login_required
def list_post(request):
    posts = Post.objects.all()
    return render(request, 'post/list.html', {'posts': posts})


@login_required
def add_post(request):
    posts = Post.objects.all()
    if request.method == 'POST':
        post_form = PostForm(request.POST)
        if post_form.is_valid():
            new_post = post_form.save(commit=False)
            new_post.author = User.objects.get(username=request.user)
            new_post.save()
            return render(request, 'post/list.html', {'posts': posts})
    else:
        post_form = PostForm()
    return render(request, 'post/addpost.html', {'post_form': post_form})


@login_required
def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post, publish__year=year,
                             publish__month=month, publish__day=day)
    comments = post.comments.filter(active=True)
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.name = User.objects.get(username=request.user)
            new_comment.post = post
            new_comment.save()
    else:
        comment_form = CommentForm()
    return render(request, 'post/detail.html', {'post': post, 'comments': comments,
                                                'comment_form': comment_form})


@login_required
def edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    posts = Post.objects.all()
    if request.user.id != post.author.id:
        return HttpResponseForbidden("Only author can edit post!")
    if request.method == 'POST':
        post_form = PostForm(request.POST, instance=post)
        if post_form.is_valid():
            post_form.save()
            return render(request, 'post/list.html', {'posts': posts})
    else:
        post_form = PostForm(instance=post)
        return render(request, 'post/editpost.html', {'post_form': post_form})


@login_required
def delete(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.user.id != post.author.id:
        return HttpResponseForbidden("Only author can delete post!")
    else:
        posts = Post.objects.all()
        post.delete()
        return render(request, 'post/list.html', {'posts': posts})

notice_board/templates/post/addpost.html
{% extends "main_page/main_page.html" %}
{% block title %}Notice Board{% endblock %}
{% block content %}

<div id="post_block">
    <h1>Adding new post:</h1>
    <br>
    <form action="." method="post">
        {{ post_form.as_p }}
        {% csrf_token %}
        <p><input type="submit" value="Add post"></p>
    </form>
</div>

{% endblock %}

notice_board/templates/post/detail.html
{% extends "main_page/main_page.html" %}

{% block title %}{{ post.title }}{% endblock %}
{% block content %}
<div id="post_block">
    <h1>{{ post.title }}</h1>
    <h4>
    <p class="date">
        {{ post.author }}
        {{ post.publish }}
    </p>
    </h4>
    <div style="padding-top: 5px; padding-bottom: 15px; border-bottom: solid 1px #b3b3b3;">
        <font size="4">
        {{ post.body }}
        </font>
    </div>
    {% for comment in comments %}
        <div class="comment">
            <h4>
            <p class="info">
                {{ comment.name }}
                commented on:
                {{ comment.created }}
            </p>
            </h4>
            <p class="body_comment">
               {{ comment.body }}
            </p>
        </div>
    {% endfor %}

    {% if new_comment %}
        <h2>Your comment is added.</h2>
    {% else %}
        <form action="." method="post">
        {{ comment_form.as_p }}
        {% csrf_token %}
        <p><input type="submit" value="Add comment"></p>
        </form>
    {% endif %}

    {% if request.user.is_superuser %}
        <div class="buttons">
            <a href="{% url 'notice_board:edit_post' pk=post.pk %}"><input type="button" value="Edit post"/></a>
            <a href="{% url 'notice_board:delete_post' pk=post.pk %}"><input type="button" value="Delete post"/></a>
        </div>
    {% endif %}
</div>
{% endblock %}

notice_board/templates/post/editpost.html
{% extends "main_page/main_page.html" %}
{% block title %}Notice Board{% endblock %}
{% block content %}

<div id="post_block">
    <h1>Editting post:</h1>
    <br>
    <form action="." method="post">
        {{ post_form.as_p }}
        {% csrf_token %}
        <p><input type="submit" value="Save changes"></p>
    </form>
</div>

{% endblock %}

notice_board/templates/post/list.html
{% extends "main_page/main_page.html" %}

{% block title %}Notice Board{% endblock %}
{% block content %}

{% if request.user.is_superuser %}
    <div class="buttons" style="margin-left: 15%; margin-bottom: 10px;">
        <a href="{% url 'notice_board:add_post' %}"><input type="button" value="Create new post"/></a>
    </div>
{% endif %}
    
{% for post in posts %}
    <div id="post_block">
        <h2>
        <a href="{{ post.get_absolute_url }}">
            {{ post.title }}
        </a>
        </h2>
        <h4>
        <p class="date">
            {{ post.author }}
            {{ post.publish }}
        </p>
        </h4>
        {{ post.body|truncatewords:30|linebreaks }}
    </div>
{% endfor %}

{% endblock %}